### ISSUE TITLE
Module libclang cannot be found

### ISSUE THREAD

**Issue by pronebird** [tjfontaine/node-libclang#6]
I use node 0.8.22 and somehow this library does not get imported. require('libclang') throws the following:

```
> require('libclang')
Error: Cannot find module 'libclang'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:109:21)
    at Interface.<anonymous> (repl.js:248:12)
    at Interface.EventEmitter.emit (events.js:96:17)
    at Interface._onLine (readline.js:200:10)
    at Interface._line (readline.js:518:8)
```

I tried the same on another machine when I have some stuff up and running and it does not work :( But the module is there.

**Comment by pronebird** [comment]
I suspect it's a bad idea to have `lib/index.js` file which basically used on node to include all library files at once...

**Comment by pronebird** [comment]
Is there any way to make it work and could you please give me some working example...

**Comment by tjfontaine** [comment]
Yes the packaging is a little screwy, I mostly only used it from the generation script. I have just pushed a change to the repo (but not npm) that allows it to be required and exports what things are currently wrapped. Unfortunately the best documentation and example about how to use the api is what you see in `lib/generateffi.js`

**Comment by pronebird** [comment]
Thanks!
